all: memprofile
memprofile: memprofile.c ../../dirfibheap.o ../../edgetypes.o ../../fibheap.o ../../graph.o ../../hashtable.o ../../hashtable_gs.o ../../hashtable_itr.o ../../hashtable_utility.o
	cc -g memprofile.c ../../dirfibheap.o ../../edgetypes.o ../../fibheap.o ../../graph.o ../../hashtable.o ../../hashtable_gs.o ../../hashtable_itr.o ../../hashtable_utility.o   -o memprofile -lm -liberty
